/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import com.uia.is12.business.ErrorBusiness; 
import java.awt.event.ActionEvent; 
import javax.swing.JButton; 
import javax.swing.JInternalFrame; 
import javax.swing.JLabel; 
import javax.swing.JScrollPane; 
import javax.swing.JTable; 
import javax.swing.JTextField;
import com.uia.is12.connection.MySQLDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class ErrorDell extends javax.swing.JInternalFrame {
private MySQLDB mysqlDB;
    /**
     * Creates new form TareaInsert
     */
    public ErrorDell() {
        initComponents();
        limpiar();
        disable();
        btdell.setEnabled(false);
        jterror.setEnabled(false);
        jterror.setEnabled(false);
        try {
            tabla();
        } catch (SQLException ex) {
            Logger.getLogger(TareaInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void disable() {
        txcoderror.setEditable(false);
    }

    public void enable() {
        txcoderror.setEditable(true);
    }

    public void limpiar() {
        txcoderror.setText("");
    }

    
     public void tabla() throws SQLException {
        mysqlDB = new MySQLDB();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo Error");
        model.addColumn("Descripcion Error");
        model.addColumn("Fecha Creacion");
        model.addColumn("Codigo Tarea");

        String sql = "select * from errores";
        ResultSet res = mysqlDB.executeQuery(sql);
        String[] fila = new String[4];
        while (res.next()) {
            fila[0] = res.getString("CodigoError");
            fila[1] = res.getString("DescripcionError");
            fila[2] = res.getString("FechaCreacion");
            fila[3] = res.getString("CodigoTarea");
            model.addRow(fila);
        }
        jterror.setModel(model);
        limpiar();
        disable();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txcoderror = new javax.swing.JTextField();
        btnew = new javax.swing.JButton();
        btdell = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jterror = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbtipo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Eliminar Errores");
        setPreferredSize(new java.awt.Dimension(700, 325));

        jLabel2.setText("Codigo de Error:");

        btnew.setText("NEW");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        btdell.setText("DELL");
        btdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdellActionPerformed(evt);
            }
        });

        jterror.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Error", "Nombre Error", "Codigo de Tarea", "Fecha Creacion"
            }
        ));
        jScrollPane1.setViewportView(jterror);

        jLabel5.setText("Conectado:");

        lbus.setText("nombreu");

        jLabel7.setText("Role:");

        lbtipo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(txcoderror, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdell, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addComponent(lbtipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(lbus)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txcoderror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lbus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbtipo))
                        .addGap(13, 13, 13)
                        .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btdell, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        enable();
        btdell.setEnabled(true);
    }//GEN-LAST:event_btnewActionPerformed

    private void btdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdellActionPerformed
        ErrorBusiness errorBl = new ErrorBusiness();
        com.uia.is12.domain.Error error = new com.uia.is12.domain.Error();
        error.setCodigoError(Integer.parseInt(txcoderror.getText()));
    try {
        errorBl.dell(error);
        } catch (Exception ex) {
            Logger.getLogger(ErrorInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    try {
        tabla();
    } catch (SQLException ex) {
        Logger.getLogger(TareaInsert.class.getName()).log(Level.SEVERE, null, ex);
    }
        disable();
        btdell.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_btdellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdell;
    private javax.swing.JButton btnew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jterror;
    public static javax.swing.JLabel lbtipo;
    public static javax.swing.JLabel lbus;
    private javax.swing.JTextField txcoderror;
    // End of variables declaration//GEN-END:variables
}
