/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import java.awt.Color;
import java.awt.Graphics;


public class ProyectoPrograView extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoView
     */
    public ProyectoPrograView() {
        
        initComponents();
        lbus.setVisible(false);
        lbtipo.setVisible(false);
        
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbus = new javax.swing.JLabel();
        lbtipo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), null));
        jDesktopPane1.setToolTipText("QA TRACKER");
        jDesktopPane1.setName("QA TRACKER"); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(700, 550));

        lbus.setText("jLabel1");

        lbtipo.setText("jLabel1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(602, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtipo)
                    .addComponent(lbus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbus)
                .addGap(18, 18, 18)
                .addComponent(lbtipo)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(lbus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbtipo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(124, 30));

        jMenu1.setText("Proyectos");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295265_Increase.png")); // NOI18N
        jMenuItem1.setText("Insertar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295375_Modify.png")); // NOI18N
        jMenuItem3.setText("Modificar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295425_cross.png")); // NOI18N
        jMenuItem4.setText("Eliminar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295472_onebit_02.png")); // NOI18N
        jMenuItem2.setText("Consultas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tareas");

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295265_Increase.png")); // NOI18N
        jMenuItem5.setText("Insertar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295375_Modify.png")); // NOI18N
        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295425_cross.png")); // NOI18N
        jMenuItem7.setText("Eliminar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295472_onebit_02.png")); // NOI18N
        jMenuItem15.setText("Consultas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Errores");

        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295265_Increase.png")); // NOI18N
        jMenuItem8.setText("Insertar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295375_Modify.png")); // NOI18N
        jMenuItem9.setText("Modificar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295425_cross.png")); // NOI18N
        jMenuItem10.setText("Eliminar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuarios");

        jMenuItem11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295265_Increase.png")); // NOI18N
        jMenuItem11.setText("Insertar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295375_Modify.png")); // NOI18N
        jMenuItem12.setText("Modificar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295425_cross.png")); // NOI18N
        jMenuItem13.setText("Eliminar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        jMenuItem14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\iconos\\1397295768_address_book_close.png")); // NOI18N
        jMenuItem14.setText("Cerrar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("QA TRACKER");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TareaDell tareaDell1 = new TareaDell();
        tareaDell1.setVisible(true);
        tareaDell1.lbus.setText(lbus.getText());
        tareaDell1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(tareaDell1);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ErrorDell errorDell1= new ErrorDell();
        errorDell1.setVisible(true);
        errorDell1.lbus.setText(lbus.getText());
        errorDell1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(errorDell1);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        UsuarioDell usuarioDell1 = new UsuarioDell();
        usuarioDell1.setVisible(true);
        usuarioDell1.lbus.setText(lbus.getText());
        usuarioDell1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(usuarioDell1);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ProyectoDell proyectoDell1 = new ProyectoDell();
        proyectoDell1.setVisible(true);
        proyectoDell1.lbus.setText(lbus.getText());
        proyectoDell1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(proyectoDell1);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ProyectoInsert proyectoInsert1 = new ProyectoInsert();
        proyectoInsert1.setVisible(true);
        proyectoInsert1.lbus.setText(lbus.getText());
        proyectoInsert1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(proyectoInsert1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ProyectoUpdate proyectoUpdate1 = new ProyectoUpdate();
        proyectoUpdate1.setVisible(true);
        proyectoUpdate1.lbus.setText(lbus.getText());
        proyectoUpdate1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(proyectoUpdate1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TareaInsert tareaInsert1 = new TareaInsert();
        tareaInsert1.setVisible(true);
        tareaInsert1.lbus.setText(lbus.getText());
        tareaInsert1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(tareaInsert1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        TareaUpdate tareaUpdate1 = new TareaUpdate();
        tareaUpdate1.setVisible(true);
        tareaUpdate1.lbus.setText(lbus.getText());
        tareaUpdate1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(tareaUpdate1);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ErrorInsert errorInsert1 = new ErrorInsert();
        errorInsert1.setVisible(true);
        errorInsert1.lbus.setText(lbus.getText());
        errorInsert1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(errorInsert1);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       ErrorUpdate errorUpdate1 = new ErrorUpdate();
        errorUpdate1.setVisible(true);
        errorUpdate1.lbus.setText(lbus.getText());
        errorUpdate1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(errorUpdate1);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        UsuarioInsert usuarioInsert1 = new UsuarioInsert();
        usuarioInsert1.setVisible(true);
        usuarioInsert1.lbus.setText(lbus.getText());
        usuarioInsert1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(usuarioInsert1);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        UsuarioUpdate usuarioUpdate1 = new UsuarioUpdate();
        usuarioUpdate1.setVisible(true);
        usuarioUpdate1.lbus.setText(lbus.getText());
        usuarioUpdate1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(usuarioUpdate1);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ProyectoConsultas proyectoconsultas1 = new ProyectoConsultas();
        proyectoconsultas1.setVisible(true);
        proyectoconsultas1.lbus.setText(lbus.getText());
        proyectoconsultas1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(proyectoconsultas1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        TareaConsultas tareaconsultas1 = new TareaConsultas();
        tareaconsultas1.setVisible(true);
        tareaconsultas1.lbus.setText(lbus.getText());
        tareaconsultas1.lbtipo.setText(lbtipo.getText());
        this.jDesktopPane1.add(tareaconsultas1);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoPrograView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoPrograView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoPrograView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoPrograView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoPrograView().setVisible(true);
                
            }
        });
        
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JLabel lbtipo;
    public static javax.swing.JLabel lbus;
    // End of variables declaration//GEN-END:variables


}
