/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import com.uia.is12.business.UsuarioBusiness;
import com.uia.is12.domain.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.uia.is12.connection.MySQLDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gabriel
 */
public class UsuarioInsert extends javax.swing.JInternalFrame {
private MySQLDB mysqlDB;
    /**
     * Creates new form Proyectos
     */
    public UsuarioInsert() {
        initComponents();
        disable();
        jtusuario.setEnabled(false);
        limpiar();
        btaddusuario.setEnabled(false);
    try {
        tabla();
    } catch (SQLException ex) {
        Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public void disable(){
        txnombreusuario.setEditable(false);
        txtipo.setEditable(false);
        txcontraseñausuario1.setEditable(false);
    }
    public void enable(){
        txnombreusuario.setEditable(true);
        txtipo.setEditable(true);
         txcontraseñausuario1.setEditable(true);
         btaddusuario.setEnabled(true);
    }
    public void limpiar(){
        txtipo.setText("");
        txnombreusuario.setText("");
         txcontraseñausuario1.setText("");
    }
    
    public void tabla() throws SQLException{
        mysqlDB = new MySQLDB();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo Usuario");
        model.addColumn("Nombre Usuario");
        model.addColumn("Tipo Usuario");
        
        String sql = "select * from usuarios";
        ResultSet res = mysqlDB.executeQuery(sql);
        String[]fila = new String[3];
        while (res.next()){
            fila[0]= res.getString("CodigoUsuario");
            fila[1]= res.getString("NombreUsuario");
            fila[2]= res.getString("TipoUsuario");
            
            model.addRow(fila);
        }
        jtusuario.setModel(model);
        limpiar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txnombreusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtusuario = new javax.swing.JTable();
        btaddusuario = new javax.swing.JButton();
        btnewusuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbus = new javax.swing.JLabel();
        txcontraseñausuario1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbtipo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Agregar Usuarios");
        setPreferredSize(new java.awt.Dimension(700, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, -1, -1));
        getContentPane().add(txnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 29, 197, -1));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 69, -1, -1));
        getContentPane().add(txtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 124, 197, -1));

        jtusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo Usuario", "Nombre Usuario", "Tipo Usuario"
            }
        ));
        jScrollPane1.setViewportView(jtusuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 670, 96));

        btaddusuario.setText("ADD");
        btaddusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btaddusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 120, 80, 30));

        btnewusuario.setText("NEW");
        btnewusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnewusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 69, 80, 30));

        jLabel6.setText("Conectado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 6, -1, -1));

        lbus.setText("nombreu");
        getContentPane().add(lbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 6, -1, -1));
        getContentPane().add(txcontraseñausuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 73, 197, -1));

        jLabel4.setText("Tipo de usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 127, -1, -1));

        jLabel7.setText("Role:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 29, -1, -1));

        lbtipo.setText("jLabel2");
        getContentPane().add(lbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 29, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddusuarioActionPerformed
    
        UsuarioBusiness usuarioBL = new UsuarioBusiness();
        Usuario usuario = new Usuario();
        usuario.setNombreUsuario(txnombreusuario.getText());
        usuario.setConstraseña(txcontraseñausuario1.getText());
        usuario.setTipo(txtipo.getText());
        try {
            usuarioBL.add(usuario);
        } catch (Exception ex) {
            Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
    try {
        tabla();
    } catch (SQLException ex) {
        Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
    }
       disable();
    }//GEN-LAST:event_btaddusuarioActionPerformed

    private void btnewusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewusuarioActionPerformed
       
        enable();
     
    }//GEN-LAST:event_btnewusuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddusuario;
    private javax.swing.JButton btnewusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtusuario;
    public static javax.swing.JLabel lbtipo;
    public static javax.swing.JLabel lbus;
    private javax.swing.JTextField txcontraseñausuario1;
    private javax.swing.JTextField txnombreusuario;
    private javax.swing.JTextField txtipo;
    // End of variables declaration//GEN-END:variables
}
