/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import com.uia.is12.business.UsuarioBusiness;
import com.uia.is12.connection.MySQLDB;
import com.uia.is12.domain.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class UsuarioDell extends javax.swing.JInternalFrame {
private MySQLDB mysqlDB;
    /**
     * Creates new form Proyectos
     */
    public UsuarioDell() {
        initComponents();
          disable();
        limpiar();
        jtusuarios.setEnabled(false);
    try {
        tabla();
    } catch (SQLException ex) {
        Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    public void disable(){
        txcodigousuario.setEditable(false);
      
    }
    public void enable(){
        txcodigousuario.setEditable(true);
        
    }
    public void limpiar(){
        txcodigousuario.setText("");
       
    }
    
    public void tabla() throws SQLException{
        mysqlDB = new MySQLDB();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo Usuario");
        model.addColumn("Nombre Usuario");
        
        String sql = "select * from usuarios";
        ResultSet res = mysqlDB.executeQuery(sql);
        String[]fila = new String[2];
        while (res.next()){
            fila[0]= res.getString("CodigoUsuario");
            fila[1]= res.getString("NombreUsuario");
            
            model.addRow(fila);
        }
        jtusuarios.setModel(model);
        limpiar();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txcodigousuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtusuarios = new javax.swing.JTable();
        btdell = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbtipo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Eliminar Usuarios");
        setPreferredSize(new java.awt.Dimension(700, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 80, -1, -1));
        getContentPane().add(txcodigousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 77, 197, -1));

        jtusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo Usuario", "Nombre Usuario"
            }
        ));
        jScrollPane1.setViewportView(jtusuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 670, 96));

        btdell.setText("DELL");
        btdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdellActionPerformed(evt);
            }
        });
        getContentPane().add(btdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, 30));

        btnew.setText("NEW");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 80, 30));

        jLabel6.setText("Conectado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 11, -1, -1));

        lbus.setText("nombreu");
        getContentPane().add(lbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 11, -1, -1));

        jLabel7.setText("Role:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 30, -1, -1));

        lbtipo.setText("jLabel2");
        getContentPane().add(lbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
      enable();
    }//GEN-LAST:event_btnewActionPerformed

    private void btdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdellActionPerformed
        UsuarioBusiness usuarioBLD = new UsuarioBusiness();
        Usuario usuario = new Usuario();
        usuario.setCodigoUsuario(Integer.parseInt(txcodigousuario.getText()));
        try {
            usuarioBLD.dell(usuario);
        } catch (Exception ex) {
            Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
        try {
        tabla();
    } catch (SQLException ex) {
        Logger.getLogger(UsuarioInsert.class.getName()).log(Level.SEVERE, null, ex);
    }
        disable();
    }//GEN-LAST:event_btdellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdell;
    private javax.swing.JButton btnew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtusuarios;
    public static javax.swing.JLabel lbtipo;
    public static javax.swing.JLabel lbus;
    private javax.swing.JTextField txcodigousuario;
    // End of variables declaration//GEN-END:variables
}
